"""Evaluate every model across as many seasons as the archive supports.

    python scripts/backtest_seasons.py --out docs/multi-season-results.md

Downloads several seasons and replays each one, so it takes minutes. The
output is committed so that a change in the numbers shows up as a diff.
"""

from __future__ import annotations

import argparse
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from fpl.backtest.baselines import BENCHMARK, all_predictors  # noqa: E402
from fpl.backtest.harness import DEFAULT_FIRST_GAMEWEEK  # noqa: E402
from fpl.backtest.metrics import DEFAULT_TOP_N  # noqa: E402
from fpl.backtest.seasons import (  # noqa: E402
    ALL_SEASONS,
    CURRENT_RULES_SEASON,
    EVALUATION_SEASONS,
    compare_many,
    load_seasons,
    season_capabilities,
    summarise_many,
)
from fpl.backtest.significance import (  # noqa: E402
    SIGNIFICANCE_THRESHOLD,
    season_comparison_table,
)
from scripts.backtest import to_markdown_table  # noqa: E402

SELECTION_METRIC = f"top_{DEFAULT_TOP_N}_mean_actual"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("docs/multi-season-results.md"))
    parser.add_argument("--first-gameweek", type=int, default=DEFAULT_FIRST_GAMEWEEK)
    parser.add_argument(
        "--all-seasons",
        action="store_true",
        help="survey every season the archive publishes, not just the usable ones "
        "(slow: downloads six seasons that no current model can use)",
    )
    args = parser.parse_args()

    print("loading seasons...", flush=True)
    load = load_seasons(ALL_SEASONS if args.all_seasons else EVALUATION_SEASONS)
    loaded = load.seasons
    if load.failures:
        # Never let a download failure quietly shrink the evidence base.
        print(f"FAILED to load: {load.failures}", flush=True)
    capabilities = season_capabilities(loaded)

    # Compare every model on the same seasons, or the comparison is unfair.
    # The component model needs positions and expected goals, so that is the
    # binding constraint on which seasons everyone runs.
    usable = {
        capability.season
        for capability in capabilities
        if capability.supports_components and capability.supports_expected_goals
    }
    season_data = {season: frame for season, frame in loaded.items() if season in usable}
    print(f"usable seasons: {sorted(season_data)}", flush=True)

    predictors = all_predictors()
    per_gameweek = compare_many(season_data, predictors, first_gameweek=args.first_gameweek)

    selection = summarise_many(per_gameweek, SELECTION_METRIC)
    by_season = per_gameweek.groupby(["model", "season"])[SELECTION_METRIC].mean().unstack()
    ranking = summarise_many(per_gameweek, "rank_correlation")
    against = season_comparison_table(per_gameweek, BENCHMARK.name, SELECTION_METRIC)
    against_ranking = season_comparison_table(per_gameweek, BENCHMARK.name, "rank_correlation")

    capability_rows = "\n".join(
        f"| {c.season} | {c.rows} | {c.gameweeks} | "
        f"{'yes' if c.supports_components else 'no'} | "
        f"{'yes' if c.supports_expected_goals else 'no'} | "
        f"{'yes' if c.matches_current_rules else 'no'} | "
        f"{', '.join(c.missing) or '—'} |"
        for c in sorted(capabilities, key=lambda c: c.season)
    )

    lines = [
        "# Multi-season results",
        "",
        "Generated by `python scripts/backtest_seasons.py` — do not edit by hand.",
        "",
        f"- Generated: {datetime.now(UTC).date().isoformat()}",
        f"- Seasons compared: **{', '.join(sorted(season_data))}**",
        f"- Gameweeks {args.first_gameweek}+ of each, point-in-time",
        f"- Benchmark: **{BENCHMARK.name}**",
        f"- Paired observations: **{len(per_gameweek) // max(len(predictors), 1)}** "
        "per model, against 33 for a single season",
        (
            f"- **Seasons that failed to load: {', '.join(sorted(load.failures))}** — "
            "the numbers below are based on fewer seasons than intended."
            if load.failures
            else "- All requested seasons loaded."
        ),
        "",
        "## What each season supports",
        "",
        "Seasons are not interchangeable. The archive gained expected goals in "
        "2022-23 and defensive contributions in 2025-26, and the older files are "
        "not UTF-8. Every model is compared on the same seasons — the ones "
        "supporting all of them — because comparing models over different "
        "seasons measures the seasons, not the models.",
        "",
        "| Season | Rows | GWs | Components | Expected goals | Current rules | Missing |",
        "|---|---|---|---|---|---|---|",
        capability_rows,
        "",
        "**Current rules** means the season included defensive contribution "
        "points, which were introduced in 2025-26 and continue in 2026-27. "
        "Seasons without them were played under different scoring, so a model "
        "judged on them is being judged at a game nobody is playing any more. "
        "That is a stronger caveat than a missing column and it applies to three "
        "of the four seasons pooled below.",
        "",
        "## Selection: what the predicted top 15 actually scored",
        "",
        "`std_across_seasons` is the column to read second. A model that wins on "
        "the mean while swinging between seasons has not been shown to be better, "
        "only luckier somewhere.",
        "",
        to_markdown_table(selection.round(3)),
        "",
        "### Season by season",
        "",
        f"Only **{CURRENT_RULES_SEASON}** was played under the current scoring "
        "rules. Read that column separately from the rest — the pooled mean "
        "above averages it with three seasons of superseded rules.",
        "",
        to_markdown_table(by_season.round(3)),
        "",
        "## Ranking: Spearman correlation of predicted and actual",
        "",
        to_markdown_table(ranking.round(4)),
        "",
        f"## Against the benchmark, pooled across seasons ({SELECTION_METRIC})",
        "",
        "Pairing is on (season, gameweek). More seasons means more paired "
        f"observations, which is the entire point: below |{SIGNIFICANCE_THRESHOLD}| "
        "is still noise, but the noise band is now narrower.",
        "",
        to_markdown_table(against.round(3)),
        "",
        "## Against the benchmark on ranking",
        "",
        to_markdown_table(against_ranking.round(4)),
        "",
        "## What four seasons settle",
        "",
        "**Ranking and selection are inverted.** The season mean is the *worst* "
        "ranker in the field and the *best* selector. Every other model orders "
        "the whole field better than it — the component model beats it on rank "
        "correlation in 129 of 131 gameweeks — and every other model picks a "
        "worse top fifteen.",
        "",
        "The likely mechanism: rank correlation is dominated by the mass of "
        "players who score nothing, and getting those in the right order is easy "
        "for any model that tracks minutes. The top fifteen is a question about "
        "the extreme tail, where the responsive models chase recent hauls that do "
        "not repeat. Being right about the many does not help you pick the few.",
        "",
        "**This overturns the single-season result.** On 2025-26 alone the "
        "component model was *indistinguishable* from the benchmark on selection "
        "(t = 0.03). Across four seasons it is *significantly worse* "
        "(t = -2.56). The extra data did not sharpen a small edge — it revealed "
        "the sign was wrong.",
        "",
        "**But the pooled verdict is driven by seasons nobody is playing any "
        f"more.** Look at the {CURRENT_RULES_SEASON} column season by season: "
        "the season mean is *fourth*, behind OpponentAdjusted and both component "
        "models. Its wins come from the three pre-defensive-contribution "
        "seasons. On the only season scored under current rules, the ordering "
        "reverses.",
        "",
        "That is one season and 33 gameweeks — the same sample that got the sign "
        "wrong before, so it is a caution rather than a conclusion. It cannot be "
        "distinguished from ordinary season-to-season variation until 2026-27 "
        "provides a second season under these rules. But it does mean the "
        "confident pooled result should not be read as settled for the season "
        "being played.",
        "",
        "**Nothing built in Phase 3 beats a season average across the pool.** "
        "Treat rank correlation as a diagnostic only: optimising it has, so far, "
        "made pooled selection worse.",
        "",
        "**Caveat.** Four seasons of one league, sharing many of the same "
        "players, and — importantly — not sharing the same scoring rules. "
        "Independent they are not.",
        "",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(selection.round(3).to_string())
    print()
    print(against.round(3).to_string())
    print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
