"""Replay the baseline models over a past season and write the results table.

    python scripts/backtest.py --season 2025-26 --out docs/model-results.md

The output is committed, so that every change to a model shows up as a diff in
the numbers rather than as a claim in a commit message.
"""

from __future__ import annotations

import argparse
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from fpl.backtest.baselines import BENCHMARK, all_predictors  # noqa: E402
from fpl.backtest.harness import DEFAULT_FIRST_GAMEWEEK, compare  # noqa: E402
from fpl.backtest.significance import (  # noqa: E402
    SIGNIFICANCE_THRESHOLD,
    comparison_table,
)
from fpl.sources.archive import fetch_season_gameweeks  # noqa: E402


def _format_cell(value) -> str:
    """Format one cell; the tables mix numbers with text like "19/33"."""
    if isinstance(value, str):
        return value
    if value != value:  # NaN
        return "—"
    return f"{value:g}"


def to_markdown_table(table) -> str:
    """Render a frame as a markdown table.

    Hand-rolled because ``DataFrame.to_markdown`` needs ``tabulate``, and one
    formatting call is not worth a dependency.
    """
    headers = [table.index.name or "model", *table.columns]
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("---" for _ in headers) + "|",
    ]
    for name, row in table.iterrows():
        cells = [str(name)] + [_format_cell(value) for value in row]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


COLUMNS = [
    "top_15_mean_actual",
    "field_mean_actual",
    "top_15_precision",
    "rank_correlation",
    "mae",
    "rmse",
    "gameweeks",
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--season", default="2025-26")
    parser.add_argument("--out", type=Path, default=Path("docs/model-results.md"))
    parser.add_argument("--first-gameweek", type=int, default=DEFAULT_FIRST_GAMEWEEK)
    args = parser.parse_args()

    season = fetch_season_gameweeks(args.season)
    predictors = all_predictors()
    table = compare(season, predictors, first_gameweek=args.first_gameweek)
    table = table[[column for column in COLUMNS if column in table.columns]]

    against_benchmark = comparison_table(
        season, predictors, BENCHMARK, first_gameweek=args.first_gameweek
    )

    lines = [
        "# Model results",
        "",
        "Generated by `python scripts/backtest.py` — do not edit by hand.",
        "",
        f"- Season: **{args.season}**",
        f"- Gameweeks {args.first_gameweek}–38, point-in-time "
        "(each prediction sees only earlier gameweeks)",
        f"- Benchmark to beat: **{BENCHMARK.name}**",
        f"- Generated: {datetime.now(UTC).date().isoformat()}",
        "",
        "## Metrics",
        "",
        "| Column | Meaning |",
        "|---|---|",
        "| `top_15_mean_actual` | **The one that matters.** Points actually scored "
        "by the predicted top 15, averaged per gameweek. |",
        "| `field_mean_actual` | What every player averaged. A model must beat this "
        "to be worth anything. |",
        "| `top_15_precision` | Share of the predicted top 15 that were in the actual top 15. |",
        "| `rank_correlation` | Spearman correlation of predicted and actual points. |",
        "| `mae` / `rmse` | Error size, in points. Diagnostic only — FPL is a ranking problem. |",
        "",
        "## Results",
        "",
        to_markdown_table(table.round(3)),
        "",
        f"## Against the benchmark ({BENCHMARK.name})",
        "",
        "Ranking a table by a metric will always produce a winner. This asks the "
        "harder question: is the gap bigger than gameweek noise? Both models are "
        "scored on the same gameweeks and the difference is taken per gameweek, "
        f"so `t_statistic` is a paired statistic. Below |{SIGNIFICANCE_THRESHOLD}| "
        "is noise.",
        "",
        to_markdown_table(against_benchmark.round(3)),
        "",
        "## Reading these results",
        "",
        "- **Better ranking does not mean better picks.** The shortest form "
        "window has the best `rank_correlation` but the worst `top_15_mean_actual`. "
        "Ordering the whole field well and choosing the best fifteen are different "
        "skills, and only the second one buys players.",
        "- **`Zero` is not a valid floor on the selection metrics.** With every "
        "prediction tied, `nlargest` returns whichever rows come first, which is not "
        "a random fifteen. Judge `Zero` on `rank_correlation` (undefined, correctly) "
        "and ignore its `top_15` figures.",
        "- **`field_mean_actual` is low** because it includes every player in the "
        "dataset, most of whom did not play. It is the right comparison for "
        '"is this model doing anything", not a realistic alternative strategy.',
        "- **One season is not proof.** These numbers come from a single season of "
        "33 scored gameweeks. Treat a small gap between models as noise — the "
        "table above says which gaps qualify.",
        "- **Nothing here has earned its way into the UI yet.** Per `CLAUDE.md`, a "
        "model needs to beat the benchmark to be wired in, and beating it means "
        "clearing the noise threshold, not merely topping the table.",
        "",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(table.round(3).to_string())
    print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
