"""Regenerate docs/data-sources.md from the lineage mapping.

    python scripts/data_sources.py

The mapping lives in ``fpl/domain/lineage.py`` and is checked against the real
feeds by ``tests/test_lineage.py``. Generating the document rather than writing
it by hand is what stops the two disagreeing.
"""

from __future__ import annotations

import argparse
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from fpl.domain.lineage import (  # noqa: E402
    ELEMENTS,
    SOURCE_DESCRIPTIONS,
    Origin,
    coverage,
    entities,
)

# Lifetime and a one-line note per feed. Kept here rather than in lineage.py
# because it is presentation, not mapping.
FEED_NOTES = {
    "bootstrap.elements": ("live only", "573 players × 105 fields; season-to-date totals"),
    "bootstrap.teams": ("live only", "20 clubs, including strength ratings"),
    "bootstrap.element_types": ("reference", "4 positions and their squad limits"),
    "bootstrap.events": ("live only", "38 gameweeks, deadlines"),
    "fixtures": ("whole season", "380 matches, published months ahead"),
    "archive": ("permanent", "third-party mirror; 43–51 columns by season"),
    "odds": ("live only", "needs `ODDS_API_KEY`; 500 requests a month free"),
}


def render() -> str:
    lines: list[str] = []
    write = lines.append
    counts = coverage()

    write("# Data sources and lineage")
    write("")
    write("Every element in the model, and where it comes from. Generated by")
    write("`python scripts/data_sources.py` from `fpl/domain/lineage.py` — do not edit")
    write("by hand. `tests/test_lineage.py` checks the mapping against the real feeds,")
    write("so this cannot quietly drift from what the sources actually publish.")
    write("")
    write(f"- **{len(ELEMENTS)} elements** across **{len(entities())} entities**")
    write(f"- **{counts['sourced']} read directly** from a source field")
    write(f"- **{counts['derived']} computed** by a named function")
    write(f"- **{counts['unsourced']} unsourceable** — every element in the model can be obtained")
    write(f"- Generated: {datetime.now(UTC).date().isoformat()}")
    write("")
    write("See `docs/data-model.md` for the entity relationships and the grain of each.")
    write("")
    write("## The feeds")
    write("")
    write("| Key | Endpoint | Lifetime | Notes |")
    write("|---|---|---|---|")
    for key, description in SOURCE_DESCRIPTIONS.items():
        lifetime, note = FEED_NOTES.get(key, ("", ""))
        write(f"| `{key}` | {description} | {lifetime} | {note} |")
    write("")
    write("**Live-only feeds are the ones that matter for persistence.** Anything")
    write("marked live only is published for *now* and never retrospectively, so the")
    write("daily capture in `fpl/store/snapshot.py` is the only record that will ever")
    write("exist of it.")
    write("")
    write("## Element mapping")
    write("")

    for entity in entities():
        write(f"### {entity}")
        write("")
        write("| Field | Origin | From | Note |")
        write("|---|---|---|---|")
        for element in (e for e in ELEMENTS if e.entity == entity):
            if element.origin is Origin.SOURCED:
                origin = "sourced"
                came_from = f"`{element.source}` → `{element.source_field}`"
            elif element.origin is Origin.DERIVED:
                origin = "derived"
                came_from = f"`{element.derived_by}`"
            else:
                origin = "**unsourced**"
                came_from = "—"
            write(f"| `{element.field}` | {origin} | {came_from} | {element.note} |")
        write("")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("docs/data-sources.md"))
    args = parser.parse_args()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(), encoding="utf-8")

    counts = coverage()
    print(f"{len(ELEMENTS)} elements: {counts}")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
